# Generated by Django 3.1.7 on 2021-03-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('ssemester', models.IntegerField(max_length=2)),
                ('semail', models.EmailField(max_length=254)),
                ('scontact', models.IntegerField(max_length=20)),
            ],
        ),
    ]
